on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: git clone https://github.com/nginxinc/docker-nginx.git
    - run: |
        cd docker-nginx/modules
        podman build --build-arg ENABLED_MODULES="brotli" -t korijn/docker-nginx-brotli:latest .
