on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'nginxinc/docker-nginx'
        path: docker-nginx
    - run: podman build --build-arg ENABLED_MODULES="brotli" -t korijn/nginx-brotli:latest .
      working-directory: docker-nginx/modules
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: podman push korijn/nginx-brotli:latest
    