on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'nginxinc/docker-nginx'
        path: docker-nginx
    - run: podman build --build-arg ENABLED_MODULES="brotli" -t korijn/nginx-brotli:latest -f Dockerfile .
      working-directory: docker-nginx/modules
    - run: podman build --build-arg ENABLED_MODULES="brotli" -t korijn/nginx-brotli:alpine -f Dockerfile.alpine .
      working-directory: docker-nginx/modules
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: |
        NGINX_VERSION=$(podman run --rm korijn/nginx-brotli:latest echo $$NGINX_VERSION)
        podman tag korijn/nginx-brotli:latest korijn/nginx-brotli:$NGINX_VERSION
        podman tag korijn/nginx-brotli:alpine korijn/nginx-brotli:$NGINX_VERSION-alpine
        podman push korijn/nginx-brotli:latest
        podman push korijn/nginx-brotli:$NGINX_VERSION
        podman push korijn/nginx-brotli:alpine
        podman push korijn/nginx-brotli:$NGINX_VERSION-alpine
